
#################################################################
#
# Selection of JurkatQC directories to generate peptide reports
#
#################################################################


setwd("Z:/LabMembers/Ozan/RetentionTimePeptides")
# Get the updated QM list

QM <- readRDS("C:/Users/ozan/Desktop/Ozan_R_utilities/Development/JurkatQCscraper/QMreportArchive.rds")

QM_subset <- QM[which(QM$DistinctPepsCSTotal.number_of. > 28000),]

QM_Franklin <- QM_subset[QM_subset$instrument == "Franklin",][1:3,]
QM_Hubble2 <- QM_subset[QM_subset$instrument == "Hubble2",][1:3,]
QM_Galileo <- QM_subset[QM_subset$instrument == "Galileo",][1:3,]


QM_Beaker <-  QM_subset[(QM_subset$instrument == "Beaker")&(QM_subset$DistinctPepsCSTotal.number_of. >40000),][1,]
QM_Yoda <- QM_subset[(QM_subset$instrument == "Yoda")&(QM_subset$DistinctPepsCSTotal.number_of. >40000),][1,]


QM.summary <- rbind(QM_Galileo,QM_Hubble2,QM_Franklin, QM_Yoda,QM_Beaker)

QM.summary <- dplyr::select(QM.summary, -FileName_instrument_match,
                            -foo)

write.csv(QM.summary, file = "Potential_JurkatQC.csv", row.names = FALSE)


################################################################################
#
# Once the report generated by Spectrum Mill, read the report and start analysis 
#
################################################################################

# Initial loading:
# pPeptide <- read.csv2("T:/JurkatQC/Galileo/2017Q2/20170501/proteinPeptideComparisonColumnsExport.S.1.ssv",
#                       stringsAsFactors = FALSE)

# Save as RDS for easy loading in future sessions
# saveRDS(pPeptide,file = "pPeptide.rds")

pPeptide <- readRDS("pPeptide.rds")

repeating.names <- names(pPeptide)[1:16]
unique.names <- names(pPeptide)[209:233]

identical(length(pPeptide$sequence), unique(length(pPeptide$sequence)) )